---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fs-functionstream-github-io-v1alpha1-function
  failurePolicy: Fail
  name: mfunction-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fs.functionstream.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fs-functionstream-github-io-v1alpha1-package
  failurePolicy: Fail
  name: mpackage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fs.functionstream.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fs-functionstream-github-io-v1alpha1-function
  failurePolicy: Fail
  name: vfunction-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fs.functionstream.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fs-functionstream-github-io-v1alpha1-package
  failurePolicy: Fail
  name: vpackage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - fs.functionstream.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - package
  sideEffects: None
