[package]
name = "function-stream-streaming-runtime-job-manager"
version.workspace = true
edition.workspace = true

[lib]
name = "function_stream_streaming_runtime_job_manager"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
function-stream-config = { path = "../config" }
function-stream-runtime-common = { path = "../runtime_common" }
function-stream-streaming-planner = { path = "../streaming_planner" }
function-stream-streaming-runtime-core = { path = "../streaming_runtime_core" }
function-stream-streaming-runtime-operators = { path = "../streaming_runtime_operators" }
protocol = { path = "../../protocol" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "sync", "time", "net", "signal"] }
tokio-stream = "0.1.18"
tracing = "0.1"
