version: 2
updates:
  - package-ecosystem: npm
    directory: '/front-end'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope