[workspace]
members = [
    "src/function-stream",
    "protocol",
    "cli/cli",
    "src/catalog",
    "src/catalog_storage",
    "src/common",
    "src/config",
    "src/coordinator",
    "src/logger",
    "src/runtime_common",
    "src/servicer",
    "src/sqlparser",
    "src/streaming_runtime",
    "src/streaming_planner",
    "src/wasm_runtime",
]
resolver = "2"
default-members = ["src/function-stream"]

# Shared crate metadata for workspace members (`version.workspace = true`, etc.).
[workspace.package]
version = "0.6.0"
edition = "2024"
