# Makefile for function-stream project

DIST_DIR = distribution/functionstream

.PHONY: clean build test help install uninstall dist build-release

help:
	@echo "Available targets:"
	@echo "  build         - Build the project (debug)"
	@echo "  build-release - Build release version and prepare distribution"
	@echo "  test          - Run tests"
	@echo "  install       - Build release and install to $(DIST_DIR)/"
	@echo "  uninstall     - Remove distribution directory"
	@echo "  dist          - Alias for build-release"
	@echo "  clean         - Remove all build artifacts and generated files"

clean:
	@echo "🧹 Cleaning all build artifacts and generated files..."
	@echo "  → Running cargo clean (workspace)..."
	cargo clean
	@echo "  → Cleaning CLI target directories..."
	@if [ -d "cli/cli/target" ]; then \
		rm -rf cli/cli/target; \
		echo "  ✓ Cleaned cli/cli/target"; \
	else \
		echo "  ℹ cli/cli/target directory does not exist (already clean)"; \
	fi
	@if [ -d "cli/rust-client/target" ]; then \
		rm -rf cli/rust-client/target; \
		echo "  ✓ Cleaned cli/rust-client/target"; \
	else \
		echo "  ℹ cli/rust-client/target directory does not exist (already clean)"; \
	fi
	@if [ -d "cli/go-client/target" ]; then \
		rm -rf cli/go-client/target; \
		echo "  ✓ Cleaned cli/go-client/target"; \
	else \
		echo "  ℹ cli/go-client/target directory does not exist (already clean)"; \
	fi
	@if [ -d "cli/java-client/target" ]; then \
		rm -rf cli/java-client/target; \
		echo "  ✓ Cleaned cli/java-client/target"; \
	else \
		echo "  ℹ cli/java-client/target directory does not exist (already clean)"; \
	fi
	@if [ -d "cli/python-client/target" ]; then \
		rm -rf cli/python-client/target; \
		echo "  ✓ Cleaned cli/python-client/target"; \
	else \
		echo "  ℹ cli/python-client/target directory does not exist (already clean)"; \
	fi
	@echo "  → Cleaning other target directories..."
	@find . -name "target" -type d -not -path "./target" -not -path "./cli/cli/target" -not -path "./cli/rust-client/target" -not -path "./cli/go-client/target" -not -path "./cli/java-client/target" -not -path "./cli/python-client/target" -exec rm -rf {} + 2>/dev/null || true
	@echo "  → Removing protocol/generated directory..."
	@if [ -d "protocol/generated" ]; then \
		rm -rf protocol/generated; \
		echo "  ✓ Cleaned protocol/generated"; \
	else \
		echo "  ℹ protocol/generated directory does not exist (already clean)"; \
	fi
	@echo "  → Removing logs directory..."
	@if [ -d "logs" ]; then \
		rm -rf logs; \
		echo "  ✓ Cleaned logs"; \
	else \
		echo "  ℹ logs directory does not exist (already clean)"; \
	fi
	@echo "  → Removing distribution directory..."
	@if [ -d "distribution" ]; then \
		rm -rf distribution; \
		echo "  ✓ Cleaned distribution"; \
	else \
		echo "  ℹ distribution directory does not exist (already clean)"; \
	fi
	@echo ""
	@echo "✅ Clean complete! All build artifacts, generated files, and distribution directories have been removed."

build:
	cargo build

test:
	cargo test

build-release:
	@echo "🔨 Building release version..."
	@echo "  ℹ If this hangs on 'Blocking waiting for file lock', other cargo processes may be running."
	@echo "  ℹ Check with: ps aux | grep cargo | grep -v grep"
	cargo build --release
	@echo "📦 Preparing distribution..."
	@mkdir -p $(DIST_DIR)/bin
	@mkdir -p $(DIST_DIR)/data
	@mkdir -p $(DIST_DIR)/conf
	@mkdir -p $(DIST_DIR)/logs
	@echo "  → Copying binary files..."
	@if [ -f target/release/function-stream ]; then \
		cp target/release/function-stream $(DIST_DIR)/bin/; \
		chmod +x $(DIST_DIR)/bin/function-stream; \
		echo "  ✓ Copied function-stream"; \
	fi
	@if [ -f target/release/cli ]; then \
		cp target/release/cli $(DIST_DIR)/bin/; \
		chmod +x $(DIST_DIR)/bin/cli; \
		echo "  ✓ Copied cli"; \
	fi
	@echo "  → Copying configuration files..."
	@if [ -f config.yaml ]; then \
		cp config.yaml $(DIST_DIR)/conf/; \
		echo "  ✓ Copied config.yaml"; \
	else \
		echo "  ⚠ Config file not found, creating default..."; \
		echo "# Function Stream Configuration" > $(DIST_DIR)/conf/config.yaml; \
		echo "# Generated by make build-release" >> $(DIST_DIR)/conf/config.yaml; \
		echo "service:" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  service_id: \"my-service-001\"" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  service_name: \"function-stream\"" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  version: \"1.0.0\"" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  host: \"127.0.0.1\"" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  port: 8080" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  debug: false" >> $(DIST_DIR)/conf/config.yaml; \
		echo "logging:" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  level: info" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  format: json" >> $(DIST_DIR)/conf/config.yaml; \
		echo "  file_path: logs/app.log" >> $(DIST_DIR)/conf/config.yaml; \
	fi
	@echo ""
	@echo "✅ Distribution prepared!"
	@echo ""
	@echo "Distribution directory: $(DIST_DIR)/"
	@echo "  bin/  - Binary executables"
	@echo "  data/ - Data directory"
	@echo "  conf/ - Configuration files"
	@echo "  logs/ - Log files directory"

dist: build-release

install: build-release
	@echo ""
	@echo "✅ Installation complete!"
	@echo ""
	@echo "Installed to: $(DIST_DIR)/"
	@echo "  bin/  - Binary executables"
	@echo "  data/ - Data directory"
	@echo "  conf/ - Configuration files"
	@echo "  logs/ - Log files directory"
	@echo ""
	@echo "To run: $(DIST_DIR)/bin/function-stream"

uninstall:
	@echo "🗑️  Uninstalling function-stream..."
	@if [ -d "$(DIST_DIR)" ]; then \
		rm -rf $(DIST_DIR); \
		echo "✅ Uninstalled from $(DIST_DIR)/"; \
	else \
		echo "ℹ Distribution directory not found: $(DIST_DIR)/"; \
	fi
