openapi: 3.0.0
info:
  title: Function Stream API
  version: 0.1.0
servers:
  - url: http://localhost:7300
    description: Local development server
paths:
  /api/v1/functions:
    get:
      summary: Returns a list of functions
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "test-func"
  /api/v1/function/{function_name}:
    post:
      summary: Starts a function
      parameters:
        - in: path
          name: function_name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Function'
      responses:
        '200':
          description: Function started successfully
        '400':
          description: Bad request, failed to parse function definition or body is empty
        '409':
          description: Conflict, function already exists
    delete:
      summary: Deletes a function
      parameters:
        - in: path
          name: function_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Function deleted successfully
        '404':
          description: Function not found
components:
  schemas:
    Function:
      type: object
      properties:
        name:
          type: string
        archive:
          type: string
        inputs:
          type: array
          items:
            type: string
        output:
          type: string
        config:
          type: object
          additionalProperties:
            type: string
      required:
        - archive
        - inputs
        - output
      example:
        name: "test-func"
        archive: "/path/to/func.wasm"
        inputs: [ "input1", "input2" ]
        output: "output"
        config: { "key": "value" }
