{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: operator-mutating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: mfunction-v1alpha1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-fs-functionstream-github-io-v1alpha1-function
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - fs.functionstream.github.io
        apiVersions:
          - v1alpha1
        resources:
          - functions
  - name: mpackage-v1alpha1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-fs-functionstream-github-io-v1alpha1-package
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - fs.functionstream.github.io
        apiVersions:
          - v1alpha1
        resources:
          - packages
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: operator-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vfunction-v1alpha1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-fs-functionstream-github-io-v1alpha1-function
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - fs.functionstream.github.io
        apiVersions:
          - v1alpha1
        resources:
          - functions
  - name: vpackage-v1alpha1.kb.io
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-fs-functionstream-github-io-v1alpha1-package
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - fs.functionstream.github.io
        apiVersions:
          - v1alpha1
        resources:
          - packages
{{- end }}
