# Default values for functionstream-operator Helm chart

image:
  repository: functionstream/operator
  tag: latest
  pullPolicy: IfNotPresent

pulsar:
  serviceURL: ""

replicaCount: 1

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

affinity: {}
nodeSelector: {}
tolerations: []

metrics:
  enabled: true
  service:
    type: ClusterIP
    port: 8080

networkPolicy:
  enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s 