[package]
name = "function-stream-config"
version.workspace = true
edition.workspace = true

[lib]
name = "function_stream_config"
path = "src/lib.rs"

[features]
default = ["python"]
python = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
uuid = { version = "1.0", features = ["v4", "v7"] }
