/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1FunctionMeshSpecPodAutoScalingBehavior
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecPodAutoScalingBehavior {
  public static final String SERIALIZED_NAME_SCALE_DOWN = "scaleDown";
  @SerializedName(SERIALIZED_NAME_SCALE_DOWN)
  private V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleDown;

  public static final String SERIALIZED_NAME_SCALE_UP = "scaleUp";
  @SerializedName(SERIALIZED_NAME_SCALE_UP)
  private V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleUp;


  public V1alpha1FunctionMeshSpecPodAutoScalingBehavior scaleDown(V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleDown) {
    
    this.scaleDown = scaleDown;
    return this;
  }

   /**
   * Get scaleDown
   * @return scaleDown
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown getScaleDown() {
    return scaleDown;
  }


  public void setScaleDown(V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleDown) {
    this.scaleDown = scaleDown;
  }


  public V1alpha1FunctionMeshSpecPodAutoScalingBehavior scaleUp(V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleUp) {
    
    this.scaleUp = scaleUp;
    return this;
  }

   /**
   * Get scaleUp
   * @return scaleUp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown getScaleUp() {
    return scaleUp;
  }


  public void setScaleUp(V1alpha1FunctionMeshSpecPodAutoScalingBehaviorScaleDown scaleUp) {
    this.scaleUp = scaleUp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecPodAutoScalingBehavior v1alpha1FunctionMeshSpecPodAutoScalingBehavior = (V1alpha1FunctionMeshSpecPodAutoScalingBehavior) o;
    return Objects.equals(this.scaleDown, v1alpha1FunctionMeshSpecPodAutoScalingBehavior.scaleDown) &&
        Objects.equals(this.scaleUp, v1alpha1FunctionMeshSpecPodAutoScalingBehavior.scaleUp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scaleDown, scaleUp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecPodAutoScalingBehavior {\n");
    sb.append("    scaleDown: ").append(toIndentedString(scaleDown)).append("\n");
    sb.append("    scaleUp: ").append(toIndentedString(scaleUp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

