/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshStatusFunctionConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1FunctionMeshStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshStatus {
  public static final String SERIALIZED_NAME_FUNCTION_CONDITIONS = "functionConditions";
  @SerializedName(SERIALIZED_NAME_FUNCTION_CONDITIONS)
  private Map<String, V1alpha1FunctionMeshStatusFunctionConditions> functionConditions = null;

  public static final String SERIALIZED_NAME_SINK_CONDITIONS = "sinkConditions";
  @SerializedName(SERIALIZED_NAME_SINK_CONDITIONS)
  private Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sinkConditions = null;

  public static final String SERIALIZED_NAME_SOURCE_CONDITIONS = "sourceConditions";
  @SerializedName(SERIALIZED_NAME_SOURCE_CONDITIONS)
  private Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sourceConditions = null;


  public V1alpha1FunctionMeshStatus functionConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> functionConditions) {
    
    this.functionConditions = functionConditions;
    return this;
  }

  public V1alpha1FunctionMeshStatus putFunctionConditionsItem(String key, V1alpha1FunctionMeshStatusFunctionConditions functionConditionsItem) {
    if (this.functionConditions == null) {
      this.functionConditions = new HashMap<>();
    }
    this.functionConditions.put(key, functionConditionsItem);
    return this;
  }

   /**
   * Get functionConditions
   * @return functionConditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V1alpha1FunctionMeshStatusFunctionConditions> getFunctionConditions() {
    return functionConditions;
  }


  public void setFunctionConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> functionConditions) {
    this.functionConditions = functionConditions;
  }


  public V1alpha1FunctionMeshStatus sinkConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sinkConditions) {
    
    this.sinkConditions = sinkConditions;
    return this;
  }

  public V1alpha1FunctionMeshStatus putSinkConditionsItem(String key, V1alpha1FunctionMeshStatusFunctionConditions sinkConditionsItem) {
    if (this.sinkConditions == null) {
      this.sinkConditions = new HashMap<>();
    }
    this.sinkConditions.put(key, sinkConditionsItem);
    return this;
  }

   /**
   * Get sinkConditions
   * @return sinkConditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V1alpha1FunctionMeshStatusFunctionConditions> getSinkConditions() {
    return sinkConditions;
  }


  public void setSinkConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sinkConditions) {
    this.sinkConditions = sinkConditions;
  }


  public V1alpha1FunctionMeshStatus sourceConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sourceConditions) {
    
    this.sourceConditions = sourceConditions;
    return this;
  }

  public V1alpha1FunctionMeshStatus putSourceConditionsItem(String key, V1alpha1FunctionMeshStatusFunctionConditions sourceConditionsItem) {
    if (this.sourceConditions == null) {
      this.sourceConditions = new HashMap<>();
    }
    this.sourceConditions.put(key, sourceConditionsItem);
    return this;
  }

   /**
   * Get sourceConditions
   * @return sourceConditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V1alpha1FunctionMeshStatusFunctionConditions> getSourceConditions() {
    return sourceConditions;
  }


  public void setSourceConditions(Map<String, V1alpha1FunctionMeshStatusFunctionConditions> sourceConditions) {
    this.sourceConditions = sourceConditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshStatus v1alpha1FunctionMeshStatus = (V1alpha1FunctionMeshStatus) o;
    return Objects.equals(this.functionConditions, v1alpha1FunctionMeshStatus.functionConditions) &&
        Objects.equals(this.sinkConditions, v1alpha1FunctionMeshStatus.sinkConditions) &&
        Objects.equals(this.sourceConditions, v1alpha1FunctionMeshStatus.sourceConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionConditions, sinkConditions, sourceConditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshStatus {\n");
    sb.append("    functionConditions: ").append(toIndentedString(functionConditions)).append("\n");
    sb.append("    sinkConditions: ").append(toIndentedString(sinkConditions)).append("\n");
    sb.append("    sourceConditions: ").append(toIndentedString(sourceConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

