/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets {
  public static final String SERIALIZED_NAME_AS_VOLUME = "asVolume";
  @SerializedName(SERIALIZED_NAME_AS_VOLUME)
  private String asVolume;

  public static final String SERIALIZED_NAME_SECRET_KEY = "secretKey";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY)
  private String secretKey;

  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  private String secretName;


  public V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets asVolume(String asVolume) {
    
    this.asVolume = asVolume;
    return this;
  }

   /**
   * Get asVolume
   * @return asVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAsVolume() {
    return asVolume;
  }


  public void setAsVolume(String asVolume) {
    this.asVolume = asVolume;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets secretKey(String secretKey) {
    
    this.secretKey = secretKey;
    return this;
  }

   /**
   * Get secretKey
   * @return secretKey
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSecretKey() {
    return secretKey;
  }


  public void setSecretKey(String secretKey) {
    this.secretKey = secretKey;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets secretName(String secretName) {
    
    this.secretName = secretName;
    return this;
  }

   /**
   * Get secretName
   * @return secretName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSecretName() {
    return secretName;
  }


  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets v1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets = (V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets) o;
    return Objects.equals(this.asVolume, v1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets.asVolume) &&
        Objects.equals(this.secretKey, v1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets.secretKey) &&
        Objects.equals(this.secretName, v1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets.secretName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asVolume, secretKey, secretName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets {\n");
    sb.append("    asVolume: ").append(toIndentedString(asVolume)).append("\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

