/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference {
  public static final String SERIALIZED_NAME_MATCH_EXPRESSIONS = "matchExpressions";
  @SerializedName(SERIALIZED_NAME_MATCH_EXPRESSIONS)
  private List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions = null;

  public static final String SERIALIZED_NAME_MATCH_FIELDS = "matchFields";
  @SerializedName(SERIALIZED_NAME_MATCH_FIELDS)
  private List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchFields = null;


  public V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference matchExpressions(List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions) {
    
    this.matchExpressions = matchExpressions;
    return this;
  }

  public V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference addMatchExpressionsItem(V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions matchExpressionsItem) {
    if (this.matchExpressions == null) {
      this.matchExpressions = new ArrayList<>();
    }
    this.matchExpressions.add(matchExpressionsItem);
    return this;
  }

   /**
   * Get matchExpressions
   * @return matchExpressions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> getMatchExpressions() {
    return matchExpressions;
  }


  public void setMatchExpressions(List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchExpressions) {
    this.matchExpressions = matchExpressions;
  }


  public V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference matchFields(List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchFields) {
    
    this.matchFields = matchFields;
    return this;
  }

  public V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference addMatchFieldsItem(V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions matchFieldsItem) {
    if (this.matchFields == null) {
      this.matchFields = new ArrayList<>();
    }
    this.matchFields.add(matchFieldsItem);
    return this;
  }

   /**
   * Get matchFields
   * @return matchFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> getMatchFields() {
    return matchFields;
  }


  public void setMatchFields(List<V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreferenceMatchExpressions> matchFields) {
    this.matchFields = matchFields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference v1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference = (V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference) o;
    return Objects.equals(this.matchExpressions, v1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference.matchExpressions) &&
        Objects.equals(this.matchFields, v1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference.matchFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchExpressions, matchFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecPodAffinityNodeAffinityPreference {\n");
    sb.append("    matchExpressions: ").append(toIndentedString(matchExpressions)).append("\n");
    sb.append("    matchFields: ").append(toIndentedString(matchFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

