/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodAwsElasticBlockStore;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodAzureDisk;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodAzureFile;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodCephfs;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodCinder;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodConfigMap;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodCsi;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodDownwardAPI;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodEmptyDir;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodFc;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodFlexVolume;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodFlocker;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodGcePersistentDisk;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodGitRepo;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodGlusterfs;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodHostPath;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodIscsi;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodNfs;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodPersistentVolumeClaim;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodPhotonPersistentDisk;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodPortworxVolume;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodProjected;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodQuobyte;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodRbd;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodScaleIO;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodSecret;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodStorageos;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodVsphereVolume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1FunctionMeshSpecPodVolumes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecPodVolumes {
  public static final String SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE = "awsElasticBlockStore";
  @SerializedName(SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE)
  private V1alpha1FunctionMeshSpecPodAwsElasticBlockStore awsElasticBlockStore;

  public static final String SERIALIZED_NAME_AZURE_DISK = "azureDisk";
  @SerializedName(SERIALIZED_NAME_AZURE_DISK)
  private V1alpha1FunctionMeshSpecPodAzureDisk azureDisk;

  public static final String SERIALIZED_NAME_AZURE_FILE = "azureFile";
  @SerializedName(SERIALIZED_NAME_AZURE_FILE)
  private V1alpha1FunctionMeshSpecPodAzureFile azureFile;

  public static final String SERIALIZED_NAME_CEPHFS = "cephfs";
  @SerializedName(SERIALIZED_NAME_CEPHFS)
  private V1alpha1FunctionMeshSpecPodCephfs cephfs;

  public static final String SERIALIZED_NAME_CINDER = "cinder";
  @SerializedName(SERIALIZED_NAME_CINDER)
  private V1alpha1FunctionMeshSpecPodCinder cinder;

  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1alpha1FunctionMeshSpecPodConfigMap configMap;

  public static final String SERIALIZED_NAME_CSI = "csi";
  @SerializedName(SERIALIZED_NAME_CSI)
  private V1alpha1FunctionMeshSpecPodCsi csi;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1alpha1FunctionMeshSpecPodDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_EMPTY_DIR = "emptyDir";
  @SerializedName(SERIALIZED_NAME_EMPTY_DIR)
  private V1alpha1FunctionMeshSpecPodEmptyDir emptyDir;

  public static final String SERIALIZED_NAME_FC = "fc";
  @SerializedName(SERIALIZED_NAME_FC)
  private V1alpha1FunctionMeshSpecPodFc fc;

  public static final String SERIALIZED_NAME_FLEX_VOLUME = "flexVolume";
  @SerializedName(SERIALIZED_NAME_FLEX_VOLUME)
  private V1alpha1FunctionMeshSpecPodFlexVolume flexVolume;

  public static final String SERIALIZED_NAME_FLOCKER = "flocker";
  @SerializedName(SERIALIZED_NAME_FLOCKER)
  private V1alpha1FunctionMeshSpecPodFlocker flocker;

  public static final String SERIALIZED_NAME_GCE_PERSISTENT_DISK = "gcePersistentDisk";
  @SerializedName(SERIALIZED_NAME_GCE_PERSISTENT_DISK)
  private V1alpha1FunctionMeshSpecPodGcePersistentDisk gcePersistentDisk;

  public static final String SERIALIZED_NAME_GIT_REPO = "gitRepo";
  @SerializedName(SERIALIZED_NAME_GIT_REPO)
  private V1alpha1FunctionMeshSpecPodGitRepo gitRepo;

  public static final String SERIALIZED_NAME_GLUSTERFS = "glusterfs";
  @SerializedName(SERIALIZED_NAME_GLUSTERFS)
  private V1alpha1FunctionMeshSpecPodGlusterfs glusterfs;

  public static final String SERIALIZED_NAME_HOST_PATH = "hostPath";
  @SerializedName(SERIALIZED_NAME_HOST_PATH)
  private V1alpha1FunctionMeshSpecPodHostPath hostPath;

  public static final String SERIALIZED_NAME_ISCSI = "iscsi";
  @SerializedName(SERIALIZED_NAME_ISCSI)
  private V1alpha1FunctionMeshSpecPodIscsi iscsi;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NFS = "nfs";
  @SerializedName(SERIALIZED_NAME_NFS)
  private V1alpha1FunctionMeshSpecPodNfs nfs;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
  private V1alpha1FunctionMeshSpecPodPersistentVolumeClaim persistentVolumeClaim;

  public static final String SERIALIZED_NAME_PHOTON_PERSISTENT_DISK = "photonPersistentDisk";
  @SerializedName(SERIALIZED_NAME_PHOTON_PERSISTENT_DISK)
  private V1alpha1FunctionMeshSpecPodPhotonPersistentDisk photonPersistentDisk;

  public static final String SERIALIZED_NAME_PORTWORX_VOLUME = "portworxVolume";
  @SerializedName(SERIALIZED_NAME_PORTWORX_VOLUME)
  private V1alpha1FunctionMeshSpecPodPortworxVolume portworxVolume;

  public static final String SERIALIZED_NAME_PROJECTED = "projected";
  @SerializedName(SERIALIZED_NAME_PROJECTED)
  private V1alpha1FunctionMeshSpecPodProjected projected;

  public static final String SERIALIZED_NAME_QUOBYTE = "quobyte";
  @SerializedName(SERIALIZED_NAME_QUOBYTE)
  private V1alpha1FunctionMeshSpecPodQuobyte quobyte;

  public static final String SERIALIZED_NAME_RBD = "rbd";
  @SerializedName(SERIALIZED_NAME_RBD)
  private V1alpha1FunctionMeshSpecPodRbd rbd;

  public static final String SERIALIZED_NAME_SCALE_I_O = "scaleIO";
  @SerializedName(SERIALIZED_NAME_SCALE_I_O)
  private V1alpha1FunctionMeshSpecPodScaleIO scaleIO;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1alpha1FunctionMeshSpecPodSecret secret;

  public static final String SERIALIZED_NAME_STORAGEOS = "storageos";
  @SerializedName(SERIALIZED_NAME_STORAGEOS)
  private V1alpha1FunctionMeshSpecPodStorageos storageos;

  public static final String SERIALIZED_NAME_VSPHERE_VOLUME = "vsphereVolume";
  @SerializedName(SERIALIZED_NAME_VSPHERE_VOLUME)
  private V1alpha1FunctionMeshSpecPodVsphereVolume vsphereVolume;


  public V1alpha1FunctionMeshSpecPodVolumes awsElasticBlockStore(V1alpha1FunctionMeshSpecPodAwsElasticBlockStore awsElasticBlockStore) {
    
    this.awsElasticBlockStore = awsElasticBlockStore;
    return this;
  }

   /**
   * Get awsElasticBlockStore
   * @return awsElasticBlockStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodAwsElasticBlockStore getAwsElasticBlockStore() {
    return awsElasticBlockStore;
  }


  public void setAwsElasticBlockStore(V1alpha1FunctionMeshSpecPodAwsElasticBlockStore awsElasticBlockStore) {
    this.awsElasticBlockStore = awsElasticBlockStore;
  }


  public V1alpha1FunctionMeshSpecPodVolumes azureDisk(V1alpha1FunctionMeshSpecPodAzureDisk azureDisk) {
    
    this.azureDisk = azureDisk;
    return this;
  }

   /**
   * Get azureDisk
   * @return azureDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodAzureDisk getAzureDisk() {
    return azureDisk;
  }


  public void setAzureDisk(V1alpha1FunctionMeshSpecPodAzureDisk azureDisk) {
    this.azureDisk = azureDisk;
  }


  public V1alpha1FunctionMeshSpecPodVolumes azureFile(V1alpha1FunctionMeshSpecPodAzureFile azureFile) {
    
    this.azureFile = azureFile;
    return this;
  }

   /**
   * Get azureFile
   * @return azureFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodAzureFile getAzureFile() {
    return azureFile;
  }


  public void setAzureFile(V1alpha1FunctionMeshSpecPodAzureFile azureFile) {
    this.azureFile = azureFile;
  }


  public V1alpha1FunctionMeshSpecPodVolumes cephfs(V1alpha1FunctionMeshSpecPodCephfs cephfs) {
    
    this.cephfs = cephfs;
    return this;
  }

   /**
   * Get cephfs
   * @return cephfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodCephfs getCephfs() {
    return cephfs;
  }


  public void setCephfs(V1alpha1FunctionMeshSpecPodCephfs cephfs) {
    this.cephfs = cephfs;
  }


  public V1alpha1FunctionMeshSpecPodVolumes cinder(V1alpha1FunctionMeshSpecPodCinder cinder) {
    
    this.cinder = cinder;
    return this;
  }

   /**
   * Get cinder
   * @return cinder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodCinder getCinder() {
    return cinder;
  }


  public void setCinder(V1alpha1FunctionMeshSpecPodCinder cinder) {
    this.cinder = cinder;
  }


  public V1alpha1FunctionMeshSpecPodVolumes configMap(V1alpha1FunctionMeshSpecPodConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1alpha1FunctionMeshSpecPodConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1alpha1FunctionMeshSpecPodVolumes csi(V1alpha1FunctionMeshSpecPodCsi csi) {
    
    this.csi = csi;
    return this;
  }

   /**
   * Get csi
   * @return csi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodCsi getCsi() {
    return csi;
  }


  public void setCsi(V1alpha1FunctionMeshSpecPodCsi csi) {
    this.csi = csi;
  }


  public V1alpha1FunctionMeshSpecPodVolumes downwardAPI(V1alpha1FunctionMeshSpecPodDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1alpha1FunctionMeshSpecPodDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1alpha1FunctionMeshSpecPodVolumes emptyDir(V1alpha1FunctionMeshSpecPodEmptyDir emptyDir) {
    
    this.emptyDir = emptyDir;
    return this;
  }

   /**
   * Get emptyDir
   * @return emptyDir
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodEmptyDir getEmptyDir() {
    return emptyDir;
  }


  public void setEmptyDir(V1alpha1FunctionMeshSpecPodEmptyDir emptyDir) {
    this.emptyDir = emptyDir;
  }


  public V1alpha1FunctionMeshSpecPodVolumes fc(V1alpha1FunctionMeshSpecPodFc fc) {
    
    this.fc = fc;
    return this;
  }

   /**
   * Get fc
   * @return fc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodFc getFc() {
    return fc;
  }


  public void setFc(V1alpha1FunctionMeshSpecPodFc fc) {
    this.fc = fc;
  }


  public V1alpha1FunctionMeshSpecPodVolumes flexVolume(V1alpha1FunctionMeshSpecPodFlexVolume flexVolume) {
    
    this.flexVolume = flexVolume;
    return this;
  }

   /**
   * Get flexVolume
   * @return flexVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodFlexVolume getFlexVolume() {
    return flexVolume;
  }


  public void setFlexVolume(V1alpha1FunctionMeshSpecPodFlexVolume flexVolume) {
    this.flexVolume = flexVolume;
  }


  public V1alpha1FunctionMeshSpecPodVolumes flocker(V1alpha1FunctionMeshSpecPodFlocker flocker) {
    
    this.flocker = flocker;
    return this;
  }

   /**
   * Get flocker
   * @return flocker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodFlocker getFlocker() {
    return flocker;
  }


  public void setFlocker(V1alpha1FunctionMeshSpecPodFlocker flocker) {
    this.flocker = flocker;
  }


  public V1alpha1FunctionMeshSpecPodVolumes gcePersistentDisk(V1alpha1FunctionMeshSpecPodGcePersistentDisk gcePersistentDisk) {
    
    this.gcePersistentDisk = gcePersistentDisk;
    return this;
  }

   /**
   * Get gcePersistentDisk
   * @return gcePersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodGcePersistentDisk getGcePersistentDisk() {
    return gcePersistentDisk;
  }


  public void setGcePersistentDisk(V1alpha1FunctionMeshSpecPodGcePersistentDisk gcePersistentDisk) {
    this.gcePersistentDisk = gcePersistentDisk;
  }


  public V1alpha1FunctionMeshSpecPodVolumes gitRepo(V1alpha1FunctionMeshSpecPodGitRepo gitRepo) {
    
    this.gitRepo = gitRepo;
    return this;
  }

   /**
   * Get gitRepo
   * @return gitRepo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodGitRepo getGitRepo() {
    return gitRepo;
  }


  public void setGitRepo(V1alpha1FunctionMeshSpecPodGitRepo gitRepo) {
    this.gitRepo = gitRepo;
  }


  public V1alpha1FunctionMeshSpecPodVolumes glusterfs(V1alpha1FunctionMeshSpecPodGlusterfs glusterfs) {
    
    this.glusterfs = glusterfs;
    return this;
  }

   /**
   * Get glusterfs
   * @return glusterfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodGlusterfs getGlusterfs() {
    return glusterfs;
  }


  public void setGlusterfs(V1alpha1FunctionMeshSpecPodGlusterfs glusterfs) {
    this.glusterfs = glusterfs;
  }


  public V1alpha1FunctionMeshSpecPodVolumes hostPath(V1alpha1FunctionMeshSpecPodHostPath hostPath) {
    
    this.hostPath = hostPath;
    return this;
  }

   /**
   * Get hostPath
   * @return hostPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodHostPath getHostPath() {
    return hostPath;
  }


  public void setHostPath(V1alpha1FunctionMeshSpecPodHostPath hostPath) {
    this.hostPath = hostPath;
  }


  public V1alpha1FunctionMeshSpecPodVolumes iscsi(V1alpha1FunctionMeshSpecPodIscsi iscsi) {
    
    this.iscsi = iscsi;
    return this;
  }

   /**
   * Get iscsi
   * @return iscsi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodIscsi getIscsi() {
    return iscsi;
  }


  public void setIscsi(V1alpha1FunctionMeshSpecPodIscsi iscsi) {
    this.iscsi = iscsi;
  }


  public V1alpha1FunctionMeshSpecPodVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1FunctionMeshSpecPodVolumes nfs(V1alpha1FunctionMeshSpecPodNfs nfs) {
    
    this.nfs = nfs;
    return this;
  }

   /**
   * Get nfs
   * @return nfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodNfs getNfs() {
    return nfs;
  }


  public void setNfs(V1alpha1FunctionMeshSpecPodNfs nfs) {
    this.nfs = nfs;
  }


  public V1alpha1FunctionMeshSpecPodVolumes persistentVolumeClaim(V1alpha1FunctionMeshSpecPodPersistentVolumeClaim persistentVolumeClaim) {
    
    this.persistentVolumeClaim = persistentVolumeClaim;
    return this;
  }

   /**
   * Get persistentVolumeClaim
   * @return persistentVolumeClaim
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodPersistentVolumeClaim getPersistentVolumeClaim() {
    return persistentVolumeClaim;
  }


  public void setPersistentVolumeClaim(V1alpha1FunctionMeshSpecPodPersistentVolumeClaim persistentVolumeClaim) {
    this.persistentVolumeClaim = persistentVolumeClaim;
  }


  public V1alpha1FunctionMeshSpecPodVolumes photonPersistentDisk(V1alpha1FunctionMeshSpecPodPhotonPersistentDisk photonPersistentDisk) {
    
    this.photonPersistentDisk = photonPersistentDisk;
    return this;
  }

   /**
   * Get photonPersistentDisk
   * @return photonPersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodPhotonPersistentDisk getPhotonPersistentDisk() {
    return photonPersistentDisk;
  }


  public void setPhotonPersistentDisk(V1alpha1FunctionMeshSpecPodPhotonPersistentDisk photonPersistentDisk) {
    this.photonPersistentDisk = photonPersistentDisk;
  }


  public V1alpha1FunctionMeshSpecPodVolumes portworxVolume(V1alpha1FunctionMeshSpecPodPortworxVolume portworxVolume) {
    
    this.portworxVolume = portworxVolume;
    return this;
  }

   /**
   * Get portworxVolume
   * @return portworxVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodPortworxVolume getPortworxVolume() {
    return portworxVolume;
  }


  public void setPortworxVolume(V1alpha1FunctionMeshSpecPodPortworxVolume portworxVolume) {
    this.portworxVolume = portworxVolume;
  }


  public V1alpha1FunctionMeshSpecPodVolumes projected(V1alpha1FunctionMeshSpecPodProjected projected) {
    
    this.projected = projected;
    return this;
  }

   /**
   * Get projected
   * @return projected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodProjected getProjected() {
    return projected;
  }


  public void setProjected(V1alpha1FunctionMeshSpecPodProjected projected) {
    this.projected = projected;
  }


  public V1alpha1FunctionMeshSpecPodVolumes quobyte(V1alpha1FunctionMeshSpecPodQuobyte quobyte) {
    
    this.quobyte = quobyte;
    return this;
  }

   /**
   * Get quobyte
   * @return quobyte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodQuobyte getQuobyte() {
    return quobyte;
  }


  public void setQuobyte(V1alpha1FunctionMeshSpecPodQuobyte quobyte) {
    this.quobyte = quobyte;
  }


  public V1alpha1FunctionMeshSpecPodVolumes rbd(V1alpha1FunctionMeshSpecPodRbd rbd) {
    
    this.rbd = rbd;
    return this;
  }

   /**
   * Get rbd
   * @return rbd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodRbd getRbd() {
    return rbd;
  }


  public void setRbd(V1alpha1FunctionMeshSpecPodRbd rbd) {
    this.rbd = rbd;
  }


  public V1alpha1FunctionMeshSpecPodVolumes scaleIO(V1alpha1FunctionMeshSpecPodScaleIO scaleIO) {
    
    this.scaleIO = scaleIO;
    return this;
  }

   /**
   * Get scaleIO
   * @return scaleIO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodScaleIO getScaleIO() {
    return scaleIO;
  }


  public void setScaleIO(V1alpha1FunctionMeshSpecPodScaleIO scaleIO) {
    this.scaleIO = scaleIO;
  }


  public V1alpha1FunctionMeshSpecPodVolumes secret(V1alpha1FunctionMeshSpecPodSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodSecret getSecret() {
    return secret;
  }


  public void setSecret(V1alpha1FunctionMeshSpecPodSecret secret) {
    this.secret = secret;
  }


  public V1alpha1FunctionMeshSpecPodVolumes storageos(V1alpha1FunctionMeshSpecPodStorageos storageos) {
    
    this.storageos = storageos;
    return this;
  }

   /**
   * Get storageos
   * @return storageos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodStorageos getStorageos() {
    return storageos;
  }


  public void setStorageos(V1alpha1FunctionMeshSpecPodStorageos storageos) {
    this.storageos = storageos;
  }


  public V1alpha1FunctionMeshSpecPodVolumes vsphereVolume(V1alpha1FunctionMeshSpecPodVsphereVolume vsphereVolume) {
    
    this.vsphereVolume = vsphereVolume;
    return this;
  }

   /**
   * Get vsphereVolume
   * @return vsphereVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodVsphereVolume getVsphereVolume() {
    return vsphereVolume;
  }


  public void setVsphereVolume(V1alpha1FunctionMeshSpecPodVsphereVolume vsphereVolume) {
    this.vsphereVolume = vsphereVolume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecPodVolumes v1alpha1FunctionMeshSpecPodVolumes = (V1alpha1FunctionMeshSpecPodVolumes) o;
    return Objects.equals(this.awsElasticBlockStore, v1alpha1FunctionMeshSpecPodVolumes.awsElasticBlockStore) &&
        Objects.equals(this.azureDisk, v1alpha1FunctionMeshSpecPodVolumes.azureDisk) &&
        Objects.equals(this.azureFile, v1alpha1FunctionMeshSpecPodVolumes.azureFile) &&
        Objects.equals(this.cephfs, v1alpha1FunctionMeshSpecPodVolumes.cephfs) &&
        Objects.equals(this.cinder, v1alpha1FunctionMeshSpecPodVolumes.cinder) &&
        Objects.equals(this.configMap, v1alpha1FunctionMeshSpecPodVolumes.configMap) &&
        Objects.equals(this.csi, v1alpha1FunctionMeshSpecPodVolumes.csi) &&
        Objects.equals(this.downwardAPI, v1alpha1FunctionMeshSpecPodVolumes.downwardAPI) &&
        Objects.equals(this.emptyDir, v1alpha1FunctionMeshSpecPodVolumes.emptyDir) &&
        Objects.equals(this.fc, v1alpha1FunctionMeshSpecPodVolumes.fc) &&
        Objects.equals(this.flexVolume, v1alpha1FunctionMeshSpecPodVolumes.flexVolume) &&
        Objects.equals(this.flocker, v1alpha1FunctionMeshSpecPodVolumes.flocker) &&
        Objects.equals(this.gcePersistentDisk, v1alpha1FunctionMeshSpecPodVolumes.gcePersistentDisk) &&
        Objects.equals(this.gitRepo, v1alpha1FunctionMeshSpecPodVolumes.gitRepo) &&
        Objects.equals(this.glusterfs, v1alpha1FunctionMeshSpecPodVolumes.glusterfs) &&
        Objects.equals(this.hostPath, v1alpha1FunctionMeshSpecPodVolumes.hostPath) &&
        Objects.equals(this.iscsi, v1alpha1FunctionMeshSpecPodVolumes.iscsi) &&
        Objects.equals(this.name, v1alpha1FunctionMeshSpecPodVolumes.name) &&
        Objects.equals(this.nfs, v1alpha1FunctionMeshSpecPodVolumes.nfs) &&
        Objects.equals(this.persistentVolumeClaim, v1alpha1FunctionMeshSpecPodVolumes.persistentVolumeClaim) &&
        Objects.equals(this.photonPersistentDisk, v1alpha1FunctionMeshSpecPodVolumes.photonPersistentDisk) &&
        Objects.equals(this.portworxVolume, v1alpha1FunctionMeshSpecPodVolumes.portworxVolume) &&
        Objects.equals(this.projected, v1alpha1FunctionMeshSpecPodVolumes.projected) &&
        Objects.equals(this.quobyte, v1alpha1FunctionMeshSpecPodVolumes.quobyte) &&
        Objects.equals(this.rbd, v1alpha1FunctionMeshSpecPodVolumes.rbd) &&
        Objects.equals(this.scaleIO, v1alpha1FunctionMeshSpecPodVolumes.scaleIO) &&
        Objects.equals(this.secret, v1alpha1FunctionMeshSpecPodVolumes.secret) &&
        Objects.equals(this.storageos, v1alpha1FunctionMeshSpecPodVolumes.storageos) &&
        Objects.equals(this.vsphereVolume, v1alpha1FunctionMeshSpecPodVolumes.vsphereVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awsElasticBlockStore, azureDisk, azureFile, cephfs, cinder, configMap, csi, downwardAPI, emptyDir, fc, flexVolume, flocker, gcePersistentDisk, gitRepo, glusterfs, hostPath, iscsi, name, nfs, persistentVolumeClaim, photonPersistentDisk, portworxVolume, projected, quobyte, rbd, scaleIO, secret, storageos, vsphereVolume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecPodVolumes {\n");
    sb.append("    awsElasticBlockStore: ").append(toIndentedString(awsElasticBlockStore)).append("\n");
    sb.append("    azureDisk: ").append(toIndentedString(azureDisk)).append("\n");
    sb.append("    azureFile: ").append(toIndentedString(azureFile)).append("\n");
    sb.append("    cephfs: ").append(toIndentedString(cephfs)).append("\n");
    sb.append("    cinder: ").append(toIndentedString(cinder)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    csi: ").append(toIndentedString(csi)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    emptyDir: ").append(toIndentedString(emptyDir)).append("\n");
    sb.append("    fc: ").append(toIndentedString(fc)).append("\n");
    sb.append("    flexVolume: ").append(toIndentedString(flexVolume)).append("\n");
    sb.append("    flocker: ").append(toIndentedString(flocker)).append("\n");
    sb.append("    gcePersistentDisk: ").append(toIndentedString(gcePersistentDisk)).append("\n");
    sb.append("    gitRepo: ").append(toIndentedString(gitRepo)).append("\n");
    sb.append("    glusterfs: ").append(toIndentedString(glusterfs)).append("\n");
    sb.append("    hostPath: ").append(toIndentedString(hostPath)).append("\n");
    sb.append("    iscsi: ").append(toIndentedString(iscsi)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nfs: ").append(toIndentedString(nfs)).append("\n");
    sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
    sb.append("    photonPersistentDisk: ").append(toIndentedString(photonPersistentDisk)).append("\n");
    sb.append("    portworxVolume: ").append(toIndentedString(portworxVolume)).append("\n");
    sb.append("    projected: ").append(toIndentedString(projected)).append("\n");
    sb.append("    quobyte: ").append(toIndentedString(quobyte)).append("\n");
    sb.append("    rbd: ").append(toIndentedString(rbd)).append("\n");
    sb.append("    scaleIO: ").append(toIndentedString(scaleIO)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    storageos: ").append(toIndentedString(storageos)).append("\n");
    sb.append("    vsphereVolume: ").append(toIndentedString(vsphereVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

