/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet {
  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_HTTP_HEADERS = "httpHeaders";
  @SerializedName(SERIALIZED_NAME_HTTP_HEADERS)
  private List<V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders> httpHeaders = null;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Object port;

  public static final String SERIALIZED_NAME_SCHEME = "scheme";
  @SerializedName(SERIALIZED_NAME_SCHEME)
  private String scheme;


  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet httpHeaders(List<V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders> httpHeaders) {
    
    this.httpHeaders = httpHeaders;
    return this;
  }

  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet addHttpHeadersItem(V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders httpHeadersItem) {
    if (this.httpHeaders == null) {
      this.httpHeaders = new ArrayList<>();
    }
    this.httpHeaders.add(httpHeadersItem);
    return this;
  }

   /**
   * Get httpHeaders
   * @return httpHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders> getHttpHeaders() {
    return httpHeaders;
  }


  public void setHttpHeaders(List<V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGetHttpHeaders> httpHeaders) {
    this.httpHeaders = httpHeaders;
  }


  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet port(Object port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getPort() {
    return port;
  }


  public void setPort(Object port) {
    this.port = port;
  }


  public V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet scheme(String scheme) {
    
    this.scheme = scheme;
    return this;
  }

   /**
   * Get scheme
   * @return scheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScheme() {
    return scheme;
  }


  public void setScheme(String scheme) {
    this.scheme = scheme;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet = (V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet) o;
    return Objects.equals(this.host, v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet.host) &&
        Objects.equals(this.httpHeaders, v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet.httpHeaders) &&
        Objects.equals(this.path, v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet.path) &&
        Objects.equals(this.port, v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet.port) &&
        Objects.equals(this.scheme, v1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet.scheme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, httpHeaders, path, port, scheme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecPodLifecyclePostStartHttpGet {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    httpHeaders: ").append(toIndentedString(httpHeaders)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

