/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1FunctionMeshSpecPulsar
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecPulsar {
  public static final String SERIALIZED_NAME_AUTH_SECRET = "authSecret";
  @SerializedName(SERIALIZED_NAME_AUTH_SECRET)
  private String authSecret;

  public static final String SERIALIZED_NAME_PULSAR_CONFIG = "pulsarConfig";
  @SerializedName(SERIALIZED_NAME_PULSAR_CONFIG)
  private String pulsarConfig;

  public static final String SERIALIZED_NAME_TLS_SECRET = "tlsSecret";
  @SerializedName(SERIALIZED_NAME_TLS_SECRET)
  private String tlsSecret;


  public V1alpha1FunctionMeshSpecPulsar authSecret(String authSecret) {
    
    this.authSecret = authSecret;
    return this;
  }

   /**
   * Get authSecret
   * @return authSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthSecret() {
    return authSecret;
  }


  public void setAuthSecret(String authSecret) {
    this.authSecret = authSecret;
  }


  public V1alpha1FunctionMeshSpecPulsar pulsarConfig(String pulsarConfig) {
    
    this.pulsarConfig = pulsarConfig;
    return this;
  }

   /**
   * Get pulsarConfig
   * @return pulsarConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPulsarConfig() {
    return pulsarConfig;
  }


  public void setPulsarConfig(String pulsarConfig) {
    this.pulsarConfig = pulsarConfig;
  }


  public V1alpha1FunctionMeshSpecPulsar tlsSecret(String tlsSecret) {
    
    this.tlsSecret = tlsSecret;
    return this;
  }

   /**
   * Get tlsSecret
   * @return tlsSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTlsSecret() {
    return tlsSecret;
  }


  public void setTlsSecret(String tlsSecret) {
    this.tlsSecret = tlsSecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecPulsar v1alpha1FunctionMeshSpecPulsar = (V1alpha1FunctionMeshSpecPulsar) o;
    return Objects.equals(this.authSecret, v1alpha1FunctionMeshSpecPulsar.authSecret) &&
        Objects.equals(this.pulsarConfig, v1alpha1FunctionMeshSpecPulsar.pulsarConfig) &&
        Objects.equals(this.tlsSecret, v1alpha1FunctionMeshSpecPulsar.tlsSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authSecret, pulsarConfig, tlsSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecPulsar {\n");
    sb.append("    authSecret: ").append(toIndentedString(authSecret)).append("\n");
    sb.append("    pulsarConfig: ").append(toIndentedString(pulsarConfig)).append("\n");
    sb.append("    tlsSecret: ").append(toIndentedString(tlsSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

