/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecGolang;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecInput;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecJava;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecOutput;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPod;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodResources;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPodVolumeMounts;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPulsar;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecPython;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecSecretsMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1FunctionMeshSpecFunctions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecFunctions {
  public static final String SERIALIZED_NAME_AUTO_ACK = "autoAck";
  @SerializedName(SERIALIZED_NAME_AUTO_ACK)
  private Boolean autoAck;

  public static final String SERIALIZED_NAME_CLASS_NAME = "className";
  @SerializedName(SERIALIZED_NAME_CLASS_NAME)
  private String className;

  public static final String SERIALIZED_NAME_CLEANUP_SUBSCRIPTION = "cleanupSubscription";
  @SerializedName(SERIALIZED_NAME_CLEANUP_SUBSCRIPTION)
  private Boolean cleanupSubscription;

  public static final String SERIALIZED_NAME_CLUSTER_NAME = "clusterName";
  @SerializedName(SERIALIZED_NAME_CLUSTER_NAME)
  private String clusterName;

  public static final String SERIALIZED_NAME_DEAD_LETTER_TOPIC = "deadLetterTopic";
  @SerializedName(SERIALIZED_NAME_DEAD_LETTER_TOPIC)
  private String deadLetterTopic;

  public static final String SERIALIZED_NAME_FORWARD_SOURCE_MESSAGE_PROPERTY = "forwardSourceMessageProperty";
  @SerializedName(SERIALIZED_NAME_FORWARD_SOURCE_MESSAGE_PROPERTY)
  private Boolean forwardSourceMessageProperty;

  public static final String SERIALIZED_NAME_FUNC_CONFIG = "funcConfig";
  @SerializedName(SERIALIZED_NAME_FUNC_CONFIG)
  private Object funcConfig;

  public static final String SERIALIZED_NAME_GOLANG = "golang";
  @SerializedName(SERIALIZED_NAME_GOLANG)
  private V1alpha1FunctionMeshSpecGolang golang;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_IMAGE_PULL_POLICY = "imagePullPolicy";
  @SerializedName(SERIALIZED_NAME_IMAGE_PULL_POLICY)
  private String imagePullPolicy;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private V1alpha1FunctionMeshSpecInput input;

  public static final String SERIALIZED_NAME_JAVA = "java";
  @SerializedName(SERIALIZED_NAME_JAVA)
  private V1alpha1FunctionMeshSpecJava java;

  public static final String SERIALIZED_NAME_LOG_TOPIC = "logTopic";
  @SerializedName(SERIALIZED_NAME_LOG_TOPIC)
  private String logTopic;

  public static final String SERIALIZED_NAME_MAX_MESSAGE_RETRY = "maxMessageRetry";
  @SerializedName(SERIALIZED_NAME_MAX_MESSAGE_RETRY)
  private Integer maxMessageRetry;

  public static final String SERIALIZED_NAME_MAX_PENDING_ASYNC_REQUESTS = "maxPendingAsyncRequests";
  @SerializedName(SERIALIZED_NAME_MAX_PENDING_ASYNC_REQUESTS)
  private Integer maxPendingAsyncRequests;

  public static final String SERIALIZED_NAME_MAX_REPLICAS = "maxReplicas";
  @SerializedName(SERIALIZED_NAME_MAX_REPLICAS)
  private Integer maxReplicas;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_OUTPUT = "output";
  @SerializedName(SERIALIZED_NAME_OUTPUT)
  private V1alpha1FunctionMeshSpecOutput output;

  public static final String SERIALIZED_NAME_POD = "pod";
  @SerializedName(SERIALIZED_NAME_POD)
  private V1alpha1FunctionMeshSpecPod pod;

  public static final String SERIALIZED_NAME_PROCESSING_GUARANTEE = "processingGuarantee";
  @SerializedName(SERIALIZED_NAME_PROCESSING_GUARANTEE)
  private String processingGuarantee;

  public static final String SERIALIZED_NAME_PULSAR = "pulsar";
  @SerializedName(SERIALIZED_NAME_PULSAR)
  private V1alpha1FunctionMeshSpecPulsar pulsar;

  public static final String SERIALIZED_NAME_PYTHON = "python";
  @SerializedName(SERIALIZED_NAME_PYTHON)
  private V1alpha1FunctionMeshSpecPython python;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private V1alpha1FunctionMeshSpecPodResources resources;

  public static final String SERIALIZED_NAME_RETAIN_KEY_ORDERING = "retainKeyOrdering";
  @SerializedName(SERIALIZED_NAME_RETAIN_KEY_ORDERING)
  private Boolean retainKeyOrdering;

  public static final String SERIALIZED_NAME_RETAIN_ORDERING = "retainOrdering";
  @SerializedName(SERIALIZED_NAME_RETAIN_ORDERING)
  private Boolean retainOrdering;

  public static final String SERIALIZED_NAME_RUNTIME_FLAGS = "runtimeFlags";
  @SerializedName(SERIALIZED_NAME_RUNTIME_FLAGS)
  private String runtimeFlags;

  public static final String SERIALIZED_NAME_SECRETS_MAP = "secretsMap";
  @SerializedName(SERIALIZED_NAME_SECRETS_MAP)
  private Map<String, V1alpha1FunctionMeshSpecSecretsMap> secretsMap = null;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_NAME = "subscriptionName";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_NAME)
  private String subscriptionName;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_POSITION = "subscriptionPosition";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_POSITION)
  private String subscriptionPosition;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  private String tenant;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Integer timeout;

  public static final String SERIALIZED_NAME_VOLUME_MOUNTS = "volumeMounts";
  @SerializedName(SERIALIZED_NAME_VOLUME_MOUNTS)
  private List<V1alpha1FunctionMeshSpecPodVolumeMounts> volumeMounts = null;


  public V1alpha1FunctionMeshSpecFunctions autoAck(Boolean autoAck) {
    
    this.autoAck = autoAck;
    return this;
  }

   /**
   * Get autoAck
   * @return autoAck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutoAck() {
    return autoAck;
  }


  public void setAutoAck(Boolean autoAck) {
    this.autoAck = autoAck;
  }


  public V1alpha1FunctionMeshSpecFunctions className(String className) {
    
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClassName() {
    return className;
  }


  public void setClassName(String className) {
    this.className = className;
  }


  public V1alpha1FunctionMeshSpecFunctions cleanupSubscription(Boolean cleanupSubscription) {
    
    this.cleanupSubscription = cleanupSubscription;
    return this;
  }

   /**
   * Get cleanupSubscription
   * @return cleanupSubscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCleanupSubscription() {
    return cleanupSubscription;
  }


  public void setCleanupSubscription(Boolean cleanupSubscription) {
    this.cleanupSubscription = cleanupSubscription;
  }


  public V1alpha1FunctionMeshSpecFunctions clusterName(String clusterName) {
    
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClusterName() {
    return clusterName;
  }


  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }


  public V1alpha1FunctionMeshSpecFunctions deadLetterTopic(String deadLetterTopic) {
    
    this.deadLetterTopic = deadLetterTopic;
    return this;
  }

   /**
   * Get deadLetterTopic
   * @return deadLetterTopic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeadLetterTopic() {
    return deadLetterTopic;
  }


  public void setDeadLetterTopic(String deadLetterTopic) {
    this.deadLetterTopic = deadLetterTopic;
  }


  public V1alpha1FunctionMeshSpecFunctions forwardSourceMessageProperty(Boolean forwardSourceMessageProperty) {
    
    this.forwardSourceMessageProperty = forwardSourceMessageProperty;
    return this;
  }

   /**
   * Get forwardSourceMessageProperty
   * @return forwardSourceMessageProperty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getForwardSourceMessageProperty() {
    return forwardSourceMessageProperty;
  }


  public void setForwardSourceMessageProperty(Boolean forwardSourceMessageProperty) {
    this.forwardSourceMessageProperty = forwardSourceMessageProperty;
  }


  public V1alpha1FunctionMeshSpecFunctions funcConfig(Object funcConfig) {
    
    this.funcConfig = funcConfig;
    return this;
  }

   /**
   * Get funcConfig
   * @return funcConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getFuncConfig() {
    return funcConfig;
  }


  public void setFuncConfig(Object funcConfig) {
    this.funcConfig = funcConfig;
  }


  public V1alpha1FunctionMeshSpecFunctions golang(V1alpha1FunctionMeshSpecGolang golang) {
    
    this.golang = golang;
    return this;
  }

   /**
   * Get golang
   * @return golang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecGolang getGolang() {
    return golang;
  }


  public void setGolang(V1alpha1FunctionMeshSpecGolang golang) {
    this.golang = golang;
  }


  public V1alpha1FunctionMeshSpecFunctions image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public V1alpha1FunctionMeshSpecFunctions imagePullPolicy(String imagePullPolicy) {
    
    this.imagePullPolicy = imagePullPolicy;
    return this;
  }

   /**
   * Get imagePullPolicy
   * @return imagePullPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImagePullPolicy() {
    return imagePullPolicy;
  }


  public void setImagePullPolicy(String imagePullPolicy) {
    this.imagePullPolicy = imagePullPolicy;
  }


  public V1alpha1FunctionMeshSpecFunctions input(V1alpha1FunctionMeshSpecInput input) {
    
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecInput getInput() {
    return input;
  }


  public void setInput(V1alpha1FunctionMeshSpecInput input) {
    this.input = input;
  }


  public V1alpha1FunctionMeshSpecFunctions java(V1alpha1FunctionMeshSpecJava java) {
    
    this.java = java;
    return this;
  }

   /**
   * Get java
   * @return java
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecJava getJava() {
    return java;
  }


  public void setJava(V1alpha1FunctionMeshSpecJava java) {
    this.java = java;
  }


  public V1alpha1FunctionMeshSpecFunctions logTopic(String logTopic) {
    
    this.logTopic = logTopic;
    return this;
  }

   /**
   * Get logTopic
   * @return logTopic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogTopic() {
    return logTopic;
  }


  public void setLogTopic(String logTopic) {
    this.logTopic = logTopic;
  }


  public V1alpha1FunctionMeshSpecFunctions maxMessageRetry(Integer maxMessageRetry) {
    
    this.maxMessageRetry = maxMessageRetry;
    return this;
  }

   /**
   * Get maxMessageRetry
   * @return maxMessageRetry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxMessageRetry() {
    return maxMessageRetry;
  }


  public void setMaxMessageRetry(Integer maxMessageRetry) {
    this.maxMessageRetry = maxMessageRetry;
  }


  public V1alpha1FunctionMeshSpecFunctions maxPendingAsyncRequests(Integer maxPendingAsyncRequests) {
    
    this.maxPendingAsyncRequests = maxPendingAsyncRequests;
    return this;
  }

   /**
   * Get maxPendingAsyncRequests
   * @return maxPendingAsyncRequests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxPendingAsyncRequests() {
    return maxPendingAsyncRequests;
  }


  public void setMaxPendingAsyncRequests(Integer maxPendingAsyncRequests) {
    this.maxPendingAsyncRequests = maxPendingAsyncRequests;
  }


  public V1alpha1FunctionMeshSpecFunctions maxReplicas(Integer maxReplicas) {
    
    this.maxReplicas = maxReplicas;
    return this;
  }

   /**
   * Get maxReplicas
   * @return maxReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxReplicas() {
    return maxReplicas;
  }


  public void setMaxReplicas(Integer maxReplicas) {
    this.maxReplicas = maxReplicas;
  }


  public V1alpha1FunctionMeshSpecFunctions name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1FunctionMeshSpecFunctions namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public V1alpha1FunctionMeshSpecFunctions output(V1alpha1FunctionMeshSpecOutput output) {
    
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecOutput getOutput() {
    return output;
  }


  public void setOutput(V1alpha1FunctionMeshSpecOutput output) {
    this.output = output;
  }


  public V1alpha1FunctionMeshSpecFunctions pod(V1alpha1FunctionMeshSpecPod pod) {
    
    this.pod = pod;
    return this;
  }

   /**
   * Get pod
   * @return pod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPod getPod() {
    return pod;
  }


  public void setPod(V1alpha1FunctionMeshSpecPod pod) {
    this.pod = pod;
  }


  public V1alpha1FunctionMeshSpecFunctions processingGuarantee(String processingGuarantee) {
    
    this.processingGuarantee = processingGuarantee;
    return this;
  }

   /**
   * Get processingGuarantee
   * @return processingGuarantee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProcessingGuarantee() {
    return processingGuarantee;
  }


  public void setProcessingGuarantee(String processingGuarantee) {
    this.processingGuarantee = processingGuarantee;
  }


  public V1alpha1FunctionMeshSpecFunctions pulsar(V1alpha1FunctionMeshSpecPulsar pulsar) {
    
    this.pulsar = pulsar;
    return this;
  }

   /**
   * Get pulsar
   * @return pulsar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPulsar getPulsar() {
    return pulsar;
  }


  public void setPulsar(V1alpha1FunctionMeshSpecPulsar pulsar) {
    this.pulsar = pulsar;
  }


  public V1alpha1FunctionMeshSpecFunctions python(V1alpha1FunctionMeshSpecPython python) {
    
    this.python = python;
    return this;
  }

   /**
   * Get python
   * @return python
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPython getPython() {
    return python;
  }


  public void setPython(V1alpha1FunctionMeshSpecPython python) {
    this.python = python;
  }


  public V1alpha1FunctionMeshSpecFunctions replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Get replicas
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1FunctionMeshSpecFunctions resources(V1alpha1FunctionMeshSpecPodResources resources) {
    
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionMeshSpecPodResources getResources() {
    return resources;
  }


  public void setResources(V1alpha1FunctionMeshSpecPodResources resources) {
    this.resources = resources;
  }


  public V1alpha1FunctionMeshSpecFunctions retainKeyOrdering(Boolean retainKeyOrdering) {
    
    this.retainKeyOrdering = retainKeyOrdering;
    return this;
  }

   /**
   * Get retainKeyOrdering
   * @return retainKeyOrdering
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRetainKeyOrdering() {
    return retainKeyOrdering;
  }


  public void setRetainKeyOrdering(Boolean retainKeyOrdering) {
    this.retainKeyOrdering = retainKeyOrdering;
  }


  public V1alpha1FunctionMeshSpecFunctions retainOrdering(Boolean retainOrdering) {
    
    this.retainOrdering = retainOrdering;
    return this;
  }

   /**
   * Get retainOrdering
   * @return retainOrdering
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRetainOrdering() {
    return retainOrdering;
  }


  public void setRetainOrdering(Boolean retainOrdering) {
    this.retainOrdering = retainOrdering;
  }


  public V1alpha1FunctionMeshSpecFunctions runtimeFlags(String runtimeFlags) {
    
    this.runtimeFlags = runtimeFlags;
    return this;
  }

   /**
   * Get runtimeFlags
   * @return runtimeFlags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRuntimeFlags() {
    return runtimeFlags;
  }


  public void setRuntimeFlags(String runtimeFlags) {
    this.runtimeFlags = runtimeFlags;
  }


  public V1alpha1FunctionMeshSpecFunctions secretsMap(Map<String, V1alpha1FunctionMeshSpecSecretsMap> secretsMap) {
    
    this.secretsMap = secretsMap;
    return this;
  }

  public V1alpha1FunctionMeshSpecFunctions putSecretsMapItem(String key, V1alpha1FunctionMeshSpecSecretsMap secretsMapItem) {
    if (this.secretsMap == null) {
      this.secretsMap = new HashMap<>();
    }
    this.secretsMap.put(key, secretsMapItem);
    return this;
  }

   /**
   * Get secretsMap
   * @return secretsMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V1alpha1FunctionMeshSpecSecretsMap> getSecretsMap() {
    return secretsMap;
  }


  public void setSecretsMap(Map<String, V1alpha1FunctionMeshSpecSecretsMap> secretsMap) {
    this.secretsMap = secretsMap;
  }


  public V1alpha1FunctionMeshSpecFunctions subscriptionName(String subscriptionName) {
    
    this.subscriptionName = subscriptionName;
    return this;
  }

   /**
   * Get subscriptionName
   * @return subscriptionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionName() {
    return subscriptionName;
  }


  public void setSubscriptionName(String subscriptionName) {
    this.subscriptionName = subscriptionName;
  }


  public V1alpha1FunctionMeshSpecFunctions subscriptionPosition(String subscriptionPosition) {
    
    this.subscriptionPosition = subscriptionPosition;
    return this;
  }

   /**
   * Get subscriptionPosition
   * @return subscriptionPosition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionPosition() {
    return subscriptionPosition;
  }


  public void setSubscriptionPosition(String subscriptionPosition) {
    this.subscriptionPosition = subscriptionPosition;
  }


  public V1alpha1FunctionMeshSpecFunctions tenant(String tenant) {
    
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTenant() {
    return tenant;
  }


  public void setTenant(String tenant) {
    this.tenant = tenant;
  }


  public V1alpha1FunctionMeshSpecFunctions timeout(Integer timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTimeout() {
    return timeout;
  }


  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }


  public V1alpha1FunctionMeshSpecFunctions volumeMounts(List<V1alpha1FunctionMeshSpecPodVolumeMounts> volumeMounts) {
    
    this.volumeMounts = volumeMounts;
    return this;
  }

  public V1alpha1FunctionMeshSpecFunctions addVolumeMountsItem(V1alpha1FunctionMeshSpecPodVolumeMounts volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * Get volumeMounts
   * @return volumeMounts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1FunctionMeshSpecPodVolumeMounts> getVolumeMounts() {
    return volumeMounts;
  }


  public void setVolumeMounts(List<V1alpha1FunctionMeshSpecPodVolumeMounts> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecFunctions v1alpha1FunctionMeshSpecFunctions = (V1alpha1FunctionMeshSpecFunctions) o;
    return Objects.equals(this.autoAck, v1alpha1FunctionMeshSpecFunctions.autoAck) &&
        Objects.equals(this.className, v1alpha1FunctionMeshSpecFunctions.className) &&
        Objects.equals(this.cleanupSubscription, v1alpha1FunctionMeshSpecFunctions.cleanupSubscription) &&
        Objects.equals(this.clusterName, v1alpha1FunctionMeshSpecFunctions.clusterName) &&
        Objects.equals(this.deadLetterTopic, v1alpha1FunctionMeshSpecFunctions.deadLetterTopic) &&
        Objects.equals(this.forwardSourceMessageProperty, v1alpha1FunctionMeshSpecFunctions.forwardSourceMessageProperty) &&
        Objects.equals(this.funcConfig, v1alpha1FunctionMeshSpecFunctions.funcConfig) &&
        Objects.equals(this.golang, v1alpha1FunctionMeshSpecFunctions.golang) &&
        Objects.equals(this.image, v1alpha1FunctionMeshSpecFunctions.image) &&
        Objects.equals(this.imagePullPolicy, v1alpha1FunctionMeshSpecFunctions.imagePullPolicy) &&
        Objects.equals(this.input, v1alpha1FunctionMeshSpecFunctions.input) &&
        Objects.equals(this.java, v1alpha1FunctionMeshSpecFunctions.java) &&
        Objects.equals(this.logTopic, v1alpha1FunctionMeshSpecFunctions.logTopic) &&
        Objects.equals(this.maxMessageRetry, v1alpha1FunctionMeshSpecFunctions.maxMessageRetry) &&
        Objects.equals(this.maxPendingAsyncRequests, v1alpha1FunctionMeshSpecFunctions.maxPendingAsyncRequests) &&
        Objects.equals(this.maxReplicas, v1alpha1FunctionMeshSpecFunctions.maxReplicas) &&
        Objects.equals(this.name, v1alpha1FunctionMeshSpecFunctions.name) &&
        Objects.equals(this.namespace, v1alpha1FunctionMeshSpecFunctions.namespace) &&
        Objects.equals(this.output, v1alpha1FunctionMeshSpecFunctions.output) &&
        Objects.equals(this.pod, v1alpha1FunctionMeshSpecFunctions.pod) &&
        Objects.equals(this.processingGuarantee, v1alpha1FunctionMeshSpecFunctions.processingGuarantee) &&
        Objects.equals(this.pulsar, v1alpha1FunctionMeshSpecFunctions.pulsar) &&
        Objects.equals(this.python, v1alpha1FunctionMeshSpecFunctions.python) &&
        Objects.equals(this.replicas, v1alpha1FunctionMeshSpecFunctions.replicas) &&
        Objects.equals(this.resources, v1alpha1FunctionMeshSpecFunctions.resources) &&
        Objects.equals(this.retainKeyOrdering, v1alpha1FunctionMeshSpecFunctions.retainKeyOrdering) &&
        Objects.equals(this.retainOrdering, v1alpha1FunctionMeshSpecFunctions.retainOrdering) &&
        Objects.equals(this.runtimeFlags, v1alpha1FunctionMeshSpecFunctions.runtimeFlags) &&
        Objects.equals(this.secretsMap, v1alpha1FunctionMeshSpecFunctions.secretsMap) &&
        Objects.equals(this.subscriptionName, v1alpha1FunctionMeshSpecFunctions.subscriptionName) &&
        Objects.equals(this.subscriptionPosition, v1alpha1FunctionMeshSpecFunctions.subscriptionPosition) &&
        Objects.equals(this.tenant, v1alpha1FunctionMeshSpecFunctions.tenant) &&
        Objects.equals(this.timeout, v1alpha1FunctionMeshSpecFunctions.timeout) &&
        Objects.equals(this.volumeMounts, v1alpha1FunctionMeshSpecFunctions.volumeMounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoAck, className, cleanupSubscription, clusterName, deadLetterTopic, forwardSourceMessageProperty, funcConfig, golang, image, imagePullPolicy, input, java, logTopic, maxMessageRetry, maxPendingAsyncRequests, maxReplicas, name, namespace, output, pod, processingGuarantee, pulsar, python, replicas, resources, retainKeyOrdering, retainOrdering, runtimeFlags, secretsMap, subscriptionName, subscriptionPosition, tenant, timeout, volumeMounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecFunctions {\n");
    sb.append("    autoAck: ").append(toIndentedString(autoAck)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    cleanupSubscription: ").append(toIndentedString(cleanupSubscription)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    deadLetterTopic: ").append(toIndentedString(deadLetterTopic)).append("\n");
    sb.append("    forwardSourceMessageProperty: ").append(toIndentedString(forwardSourceMessageProperty)).append("\n");
    sb.append("    funcConfig: ").append(toIndentedString(funcConfig)).append("\n");
    sb.append("    golang: ").append(toIndentedString(golang)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imagePullPolicy: ").append(toIndentedString(imagePullPolicy)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    java: ").append(toIndentedString(java)).append("\n");
    sb.append("    logTopic: ").append(toIndentedString(logTopic)).append("\n");
    sb.append("    maxMessageRetry: ").append(toIndentedString(maxMessageRetry)).append("\n");
    sb.append("    maxPendingAsyncRequests: ").append(toIndentedString(maxPendingAsyncRequests)).append("\n");
    sb.append("    maxReplicas: ").append(toIndentedString(maxReplicas)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    pod: ").append(toIndentedString(pod)).append("\n");
    sb.append("    processingGuarantee: ").append(toIndentedString(processingGuarantee)).append("\n");
    sb.append("    pulsar: ").append(toIndentedString(pulsar)).append("\n");
    sb.append("    python: ").append(toIndentedString(python)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    retainKeyOrdering: ").append(toIndentedString(retainKeyOrdering)).append("\n");
    sb.append("    retainOrdering: ").append(toIndentedString(retainOrdering)).append("\n");
    sb.append("    runtimeFlags: ").append(toIndentedString(runtimeFlags)).append("\n");
    sb.append("    secretsMap: ").append(toIndentedString(secretsMap)).append("\n");
    sb.append("    subscriptionName: ").append(toIndentedString(subscriptionName)).append("\n");
    sb.append("    subscriptionPosition: ").append(toIndentedString(subscriptionPosition)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

