/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.functionmesh.compute.mesh.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.functionmesh.compute.mesh.models.V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * V1alpha1FunctionMeshSpecInputCryptoConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-10-07T12:35:29.394Z[Etc/UTC]")
public class V1alpha1FunctionMeshSpecInputCryptoConfig {
  public static final String SERIALIZED_NAME_CONSUMER_CRYPTO_FAILURE_ACTION = "consumerCryptoFailureAction";
  @SerializedName(SERIALIZED_NAME_CONSUMER_CRYPTO_FAILURE_ACTION)
  private String consumerCryptoFailureAction;

  public static final String SERIALIZED_NAME_CRYPTO_KEY_READER_CLASS_NAME = "cryptoKeyReaderClassName";
  @SerializedName(SERIALIZED_NAME_CRYPTO_KEY_READER_CLASS_NAME)
  private String cryptoKeyReaderClassName;

  public static final String SERIALIZED_NAME_CRYPTO_KEY_READER_CONFIG = "cryptoKeyReaderConfig";
  @SerializedName(SERIALIZED_NAME_CRYPTO_KEY_READER_CONFIG)
  private Map<String, String> cryptoKeyReaderConfig = null;

  public static final String SERIALIZED_NAME_CRYPTO_SECRETS = "cryptoSecrets";
  @SerializedName(SERIALIZED_NAME_CRYPTO_SECRETS)
  private List<V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets> cryptoSecrets = null;

  public static final String SERIALIZED_NAME_ENCRYPTION_KEYS = "encryptionKeys";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION_KEYS)
  private List<String> encryptionKeys = null;

  public static final String SERIALIZED_NAME_PRODUCER_CRYPTO_FAILURE_ACTION = "producerCryptoFailureAction";
  @SerializedName(SERIALIZED_NAME_PRODUCER_CRYPTO_FAILURE_ACTION)
  private String producerCryptoFailureAction;


  public V1alpha1FunctionMeshSpecInputCryptoConfig consumerCryptoFailureAction(String consumerCryptoFailureAction) {
    
    this.consumerCryptoFailureAction = consumerCryptoFailureAction;
    return this;
  }

   /**
   * Get consumerCryptoFailureAction
   * @return consumerCryptoFailureAction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConsumerCryptoFailureAction() {
    return consumerCryptoFailureAction;
  }


  public void setConsumerCryptoFailureAction(String consumerCryptoFailureAction) {
    this.consumerCryptoFailureAction = consumerCryptoFailureAction;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfig cryptoKeyReaderClassName(String cryptoKeyReaderClassName) {
    
    this.cryptoKeyReaderClassName = cryptoKeyReaderClassName;
    return this;
  }

   /**
   * Get cryptoKeyReaderClassName
   * @return cryptoKeyReaderClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCryptoKeyReaderClassName() {
    return cryptoKeyReaderClassName;
  }


  public void setCryptoKeyReaderClassName(String cryptoKeyReaderClassName) {
    this.cryptoKeyReaderClassName = cryptoKeyReaderClassName;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfig cryptoKeyReaderConfig(Map<String, String> cryptoKeyReaderConfig) {
    
    this.cryptoKeyReaderConfig = cryptoKeyReaderConfig;
    return this;
  }

  public V1alpha1FunctionMeshSpecInputCryptoConfig putCryptoKeyReaderConfigItem(String key, String cryptoKeyReaderConfigItem) {
    if (this.cryptoKeyReaderConfig == null) {
      this.cryptoKeyReaderConfig = new HashMap<>();
    }
    this.cryptoKeyReaderConfig.put(key, cryptoKeyReaderConfigItem);
    return this;
  }

   /**
   * Get cryptoKeyReaderConfig
   * @return cryptoKeyReaderConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getCryptoKeyReaderConfig() {
    return cryptoKeyReaderConfig;
  }


  public void setCryptoKeyReaderConfig(Map<String, String> cryptoKeyReaderConfig) {
    this.cryptoKeyReaderConfig = cryptoKeyReaderConfig;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfig cryptoSecrets(List<V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets> cryptoSecrets) {
    
    this.cryptoSecrets = cryptoSecrets;
    return this;
  }

  public V1alpha1FunctionMeshSpecInputCryptoConfig addCryptoSecretsItem(V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets cryptoSecretsItem) {
    if (this.cryptoSecrets == null) {
      this.cryptoSecrets = new ArrayList<>();
    }
    this.cryptoSecrets.add(cryptoSecretsItem);
    return this;
  }

   /**
   * Get cryptoSecrets
   * @return cryptoSecrets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets> getCryptoSecrets() {
    return cryptoSecrets;
  }


  public void setCryptoSecrets(List<V1alpha1FunctionMeshSpecInputCryptoConfigCryptoSecrets> cryptoSecrets) {
    this.cryptoSecrets = cryptoSecrets;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfig encryptionKeys(List<String> encryptionKeys) {
    
    this.encryptionKeys = encryptionKeys;
    return this;
  }

  public V1alpha1FunctionMeshSpecInputCryptoConfig addEncryptionKeysItem(String encryptionKeysItem) {
    if (this.encryptionKeys == null) {
      this.encryptionKeys = new ArrayList<>();
    }
    this.encryptionKeys.add(encryptionKeysItem);
    return this;
  }

   /**
   * Get encryptionKeys
   * @return encryptionKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEncryptionKeys() {
    return encryptionKeys;
  }


  public void setEncryptionKeys(List<String> encryptionKeys) {
    this.encryptionKeys = encryptionKeys;
  }


  public V1alpha1FunctionMeshSpecInputCryptoConfig producerCryptoFailureAction(String producerCryptoFailureAction) {
    
    this.producerCryptoFailureAction = producerCryptoFailureAction;
    return this;
  }

   /**
   * Get producerCryptoFailureAction
   * @return producerCryptoFailureAction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProducerCryptoFailureAction() {
    return producerCryptoFailureAction;
  }


  public void setProducerCryptoFailureAction(String producerCryptoFailureAction) {
    this.producerCryptoFailureAction = producerCryptoFailureAction;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionMeshSpecInputCryptoConfig v1alpha1FunctionMeshSpecInputCryptoConfig = (V1alpha1FunctionMeshSpecInputCryptoConfig) o;
    return Objects.equals(this.consumerCryptoFailureAction, v1alpha1FunctionMeshSpecInputCryptoConfig.consumerCryptoFailureAction) &&
        Objects.equals(this.cryptoKeyReaderClassName, v1alpha1FunctionMeshSpecInputCryptoConfig.cryptoKeyReaderClassName) &&
        Objects.equals(this.cryptoKeyReaderConfig, v1alpha1FunctionMeshSpecInputCryptoConfig.cryptoKeyReaderConfig) &&
        Objects.equals(this.cryptoSecrets, v1alpha1FunctionMeshSpecInputCryptoConfig.cryptoSecrets) &&
        Objects.equals(this.encryptionKeys, v1alpha1FunctionMeshSpecInputCryptoConfig.encryptionKeys) &&
        Objects.equals(this.producerCryptoFailureAction, v1alpha1FunctionMeshSpecInputCryptoConfig.producerCryptoFailureAction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerCryptoFailureAction, cryptoKeyReaderClassName, cryptoKeyReaderConfig, cryptoSecrets, encryptionKeys, producerCryptoFailureAction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionMeshSpecInputCryptoConfig {\n");
    sb.append("    consumerCryptoFailureAction: ").append(toIndentedString(consumerCryptoFailureAction)).append("\n");
    sb.append("    cryptoKeyReaderClassName: ").append(toIndentedString(cryptoKeyReaderClassName)).append("\n");
    sb.append("    cryptoKeyReaderConfig: ").append(toIndentedString(cryptoKeyReaderConfig)).append("\n");
    sb.append("    cryptoSecrets: ").append(toIndentedString(cryptoSecrets)).append("\n");
    sb.append("    encryptionKeys: ").append(toIndentedString(encryptionKeys)).append("\n");
    sb.append("    producerCryptoFailureAction: ").append(toIndentedString(producerCryptoFailureAction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

