#!/usr/bin/env python3
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Code generation script for Function Stream Python Client

Generates Python code from .proto files and fixes import issues.
"""

import os
import sys
from grpc_tools import protoc


def generate():
    """Generate Python code from proto files."""
    # 1. 定义路径
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    proto_dir = os.path.join(project_root, "protos")
    out_dir = os.path.join(project_root, "src", "fs_client", "_proto")

    print(f"Project root: {project_root}")
    print(f"Proto directory: {proto_dir}")
    print(f"Output directory: {out_dir}")

    # 2. 确保输出目录存在
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
        print(f"Created output directory: {out_dir}")

    # 创建 __init__.py 保证它是 Python 包
    init_file = os.path.join(out_dir, "__init__.py")
    with open(init_file, "w") as f:
        f.write("# Generated by scripts/codegen.py\n")
        f.write("# This package contains generated protobuf code.\n")
        f.write("# Do not edit these files manually.\n")
    print(f"Created {init_file}")

    # 3. 查找所有 .proto 文件
    if not os.path.exists(proto_dir):
        print(f"Error: Proto directory not found: {proto_dir}")
        sys.exit(1)

    proto_files = [f for f in os.listdir(proto_dir) if f.endswith(".proto")]
    if not proto_files:
        print(f"Error: No .proto files found in {proto_dir}")
        sys.exit(1)

    print(f"Found {len(proto_files)} proto file(s)")

    # 4. 生成代码
    for proto_file in proto_files:
        source = os.path.join(proto_dir, proto_file)
        print(f"\nGenerating code for {proto_file}...")

        # 构造 protoc 命令参数
        # 注意：mypy-protobuf 需要作为插件传递
        args = [
            "",
            f"-I{proto_dir}",
            f"--python_out={out_dir}",
            f"--grpc_python_out={out_dir}",
        ]

        # 尝试添加 mypy 插件（如果可用）
        try:
            import mypy_protobuf
            args.extend([
                f"--mypy_out={out_dir}",
                f"--mypy_grpc_out={out_dir}",
            ])
            print("  Using mypy-protobuf for type hints")
        except ImportError:
            print("  Warning: mypy-protobuf not installed, skipping .pyi generation")
            print("  Install it with: pip install mypy-protobuf")

        args.append(source)

        # 运行 protoc
        try:
            exit_code = protoc.main(args)
            if exit_code != 0:
                print(f"  Error: protoc exited with code {exit_code}")
                sys.exit(1)
            print(f"  ✓ Generated Python code")
        except Exception as e:
            print(f"  Error running protoc: {e}")
            sys.exit(1)

    # 5. 修复生成的 Import 问题
    print("\nFixing imports...")
    fixed_count = 0
    for filename in os.listdir(out_dir):
        if filename.endswith("_pb2_grpc.py"):
            filepath = os.path.join(out_dir, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()

            # 查找需要修复的导入语句
            # 将 "import function_stream_pb2" 替换为 "from . import function_stream_pb2"
            original_content = content
            # 匹配各种可能的导入格式
            import_patterns = [
                (r'^import function_stream_pb2 as function__stream__pb2$', 'from . import function_stream_pb2 as function__stream__pb2'),
                (r'^import function_stream_pb2$', 'from . import function_stream_pb2'),
            ]

            import re
            for pattern, replacement in import_patterns:
                content = re.sub(pattern, replacement, content, flags=re.MULTILINE)

            if content != original_content:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"  ✓ Fixed imports in {filename}")
                fixed_count += 1
            else:
                print(f"  - No import fixes needed in {filename}")

    if fixed_count > 0:
        print(f"\n✓ Fixed imports in {fixed_count} file(s)")
    else:
        print("\n- No import fixes needed")

    print("\n✅ Code generation completed successfully!")
    print(f"\nGenerated files in: {out_dir}")
    for f in os.listdir(out_dir):
        if f.endswith((".py", ".pyi")):
            print(f"  - {f}")


if __name__ == "__main__":
    generate()

