apiVersion: fs.functionstream.github.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  # TODO(user): Add fields here
