apiVersion: fs.functionstream.github.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  displayName: "Sample Function"
  description: "A sample function for demonstration purposes."
  packageRef:
    name: "sample-package"
    # namespace: "default"  # Optional: defaults to the same namespace as the Function
  module: "sample-module"
  # TODO(user): Add fields here
