apiVersion: compute.functionmesh.io/v1alpha1
kind: FunctionMesh
metadata:
  name: functionmesh-sample
spec:
  functions:
    - image: streamnative/pulsar-functions-go-sample:2.8.1 # using function image here
      name: test-ex
      autoAck: true
      className: exclamation_function.ExclamationFunction
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 5
      logTopic: persistent://public/default/logging-function-logs
      input:
        topics:
        - persistent://public/default/a1
        typeClassName: java.lang.String
      output:
        topic: persistent://public/default/a2
        typeClassName: java.lang.String
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      resources:
        requests:
          cpu: "0.1"
          memory: 10M
        limits:
          cpu: "0.2"
          memory: 200M
      golang:
        go: /pulsar/examples/go-exclamation-func
    - image: streamnative/pulsar-functions-go-sample:2.8.1 # using function image here
      name: test-ex2
      autoAck: true
      className: exclamation_function.ExclamationFunction
      forwardSourceMessageProperty: true
      MaxPendingAsyncRequests: 1000
      replicas: 1
      maxReplicas: 5
      logTopic: persistent://public/default/logging-function-logs
      input:
        topics:
        - persistent://public/default/a2
        typeClassName: java.lang.String
      output:
        topic: persistent://public/default/a3
        typeClassName: java.lang.String
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      resources:
        requests:
          cpu: "0.1"
          memory: 10M
        limits:
          cpu: "0.2"
          memory: 200M
      golang:
        go: /pulsar/examples/go-exclamation-func
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-test-pulsar
data:
  webServiceURL: http://pulsar-svr:8080
  brokerServiceURL: pulsar://pulsar-svr:6650