name: CI - Frontend
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - branch-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: yarn install
        working-directory: front-end

      - name: Run eslint
        run: npx eslint . --ext .js,.jsx,.ts,.vue,.tsx
        working-directory: front-end

      - name: Build
        run: yarn build
        working-directory: front-end
