name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.30.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=10m
          skip-pkg-cache: true
      - run: docker-compose -f ./tests/docker-compose.yaml up -d
      - run: make build_all
      - name: Wait for Pulsar service
        run: until curl http://localhost:8080/metrics > /dev/null 2>&1 ; do sleep 1; done
      - run: nohup bin/function-stream server > nohup.out &
      - run: make test
      - name: Collect Docker Compose logs
        if: failure()
        run: docker-compose -f ./tests/docker-compose.yaml logs || true
      - name: Collect nohup logs
        if: failure()
        run: cat nohup.out || true
