name: Eslint Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install dependencies
        run: |
          npm install eslint@5.16.0 --save-dev
          npm install @vue/eslint-config-standard@4.0.0 --save-dev
          npm install eslint-plugin-vue@5.2.3 --save-dev
          npm install babel-eslint@10.0.1 --save-dev
          npm install eslint-plugin-html@5.0.0 --save-dev
        working-directory: front-end

      - name: run eslint
        run: npx eslint . --ext .js,.jsx,.ts,.vue,.tsx
        working-directory: front-end
