name: CI - Function flow controller unit tests

on: 
  pull_request:
    branches: [ main ]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run unit tests
        run: mvn clean install -f function-flow-manager

      - name: Upload surefire-reports
        uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        continue-on-error: true
        with:
          name: surefire-reports
          path: function-flow-manager/target/surefire-reports
