pulsar:
  service_url: "pulsar://localhost:6650" # Required
  authPlugin: "" # Optional
  authParams: "" # Optional
module: "string" # Required
sources: # Optional，但是sources和requestSource不能同时为空
  - pulsar: # 这里你定义成SourceSpec结构，SourceSpec下有一个pulsar的字段，这是为了后面拓展到其他消息队列准备的
      topic: "topic-a"
subscriptionName: "test-sub"
requestSource:
  - pulsar: # 这里定义成SourceSpec结构，SourceSpec下有一个pulsar的字段，这是为了后面拓展到其他消息队列准备的
      topic: "string-topic"
sink: # Optional
  pulsar: # 这里定义成SinkSpec结构，SinkSpec下有一个pulsar的字段，这是为了后面拓展到其他消息队列准备的
    topic: "output"
config: # Optional
  - test: "Hello from config"
  - test2: "Another config value"