name: my_function
type: pulsar
modules:
  string:
    name: string_process
    description: 在字符串后面添加感叹号
    inputSchema:
      type: object
      properties:
        text:
          type: string
      required:
        - text
    outputSchema:
      type: object
      properties:
        result:
          type: string