# FunctionStream Package Configuration
# This file defines the package metadata and function specifications for deployment.

# Package name and type
name: my_function  # Name of the function package
type: pulsar      # Type of message broker to use

# Module definitions
modules:
  string:  # Module name
    name: string_process  # Function name
    description: "Appends an exclamation mark to the input string"  # Function description
    
    # Input schema definition
    inputSchema:
      type: object
      properties:
        text:  # Input parameter
          type: string  # Parameter type
      required:
        - text  # Required parameter
    
    # Output schema definition
    outputSchema:
      type: object
      properties:
        result:  # Output parameter
          type: string  # Parameter type