# Copyright 2024 Function Stream Org.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FunctionStream Package Configuration
# This file defines the package metadata and function specifications for deployment.

# Package name and type
name: my_function  # Name of the function package
type: pulsar      # Type of message broker to use

# Module definitions
modules:
  string:  # Module name
    name: string_process  # Function name
    description: "Appends an exclamation mark to the input string"  # Function description
    
    # Input schema definition
    inputSchema:
      type: object
      properties:
        text:  # Input parameter
          type: string  # Parameter type
      required:
        - text  # Required parameter
    
    # Output schema definition
    outputSchema:
      type: object
      properties:
        result:  # Output parameter
          type: string  # Parameter type